const assert=require('assert');
const fs=require('fs');
const path=require('path');
const css=fs.readFileSync(path.join(__dirname,'../css/styles.css'),'utf8');
const app=fs.readFileSync(path.join(__dirname,'../js/app.js'),'utf8');
const storage=fs.readFileSync(path.join(__dirname,'../js/storage.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');

assert(css.includes('.player-two .card.selected'),'Player 2 needs a distinct selected-card style.');
assert(css.includes(':focus-visible'),'Keyboard focus must remain visible.');
assert(css.includes('prefers-reduced-motion'),'Reduced-motion preferences must be respected.');
assert(/min-height:(?:44|45|46)px/.test(css),'Controls need mobile-sized touch targets.');
assert(app.includes("'player-one':'player-two'"),'Player identity classes must be assigned during selection.');
assert(app.includes('Choose ${3-p.selected.length} More'),'Lock In must explain its disabled state.');
assert(app.includes('result-row ${i===winner'), 'Round results must highlight the winner.');
assert(css.includes('.price{position:static'), 'Card prices must remain in normal flow below variable-length text.');
assert(css.includes('.card-footer'), 'Card prices need a dedicated footer separated from traits and Appeal details.');
assert(app.includes('function instantiate(ids)'), 'Each physical drink copy must receive a unique identity.');
assert(app.includes('data-instance="${d.instanceId}"'), 'Rendered cards must expose their unique instance identity.');
assert(app.includes('if(p.tokens<=0){finishSwitch();return}'), 'Bartender selection must skip players without a switch token.');
assert(app.includes("state.mode==='pvp'&&state.players[1].tokens>0"), 'PvP pass screen must require a Player 2 switch token.');
assert(app.includes('class="match-hud"')&&app.includes('role="progressbar"'),'The match needs a clear score, round, and progress HUD.');
assert(app.includes('function appealDetails(')&&app.includes('appeal-breakdown'),'Every drink must expose its exact Appeal calculation.');
assert(app.includes('Customer preferences')&&app.includes('pref-value'),'Customer Love, Like, and Dislike values must stay visible.');
assert(app.includes('switch-token')&&app.includes('Earn more at $15, $30, and $45'),'Switch availability and thresholds must be obvious.');
assert(css.includes('.decision-bar{position:sticky'),'The Lock In decision area must remain available during long hands.');
assert(css.includes('@media(max-width:560px)')&&css.includes('@media(max-width:370px)'),'Phone and narrow-phone layouts must be explicit.');
assert(html.includes('v0.6.1a · Deck Save Hotfix'),'The browser build must identify the current hotfix.');
assert(html.indexOf('js/storage.js')<html.indexOf('js/app.js'),'Deck storage must load before the game app.');
assert(app.includes('role="status"')&&storage.includes('Deck saved'),'Deck saving must provide visible status feedback.');
assert(app.includes("home(result.message,result.persistent?'success':'warning')"),'The home screen must distinguish permanent and session-only saves.');
assert(app.includes('Not saved — ${v.message}'),'Invalid decks must explain why Save did not proceed.');
assert(!app.includes('<img'),'Prompt 14 must not repeat a promotional collage as card art.');
console.log('All Prompt 14 interface contract tests passed.');
