(function(){
const D=BLC_DATA,R=BLC_RULES,AI=BLC_AI,T=BLC_TUTORIAL,app=document.querySelector('#app');let state=null,draft=null,tutorial=null;const $=(s)=>document.querySelector(s),shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function starter(){return D.drinks.slice(0,10).flatMap(d=>[d.id,d.id,d.id])}function load(){try{const x=JSON.parse(localStorage.getItem('blc.deck'));if(R.validateDeck(x,D.drinks).ok)return x}catch(e){}return starter()}function save(ids){try{localStorage.setItem('blc.deck',JSON.stringify(ids))}catch(e){}}
function home(){state=null;tutorial=null;app.innerHTML=`<section class="panel hero"><p class="eyebrow">COMPETITIVE STRATEGY CARD GAME</p><h2>Read the room. Pour the perfect drink.</h2><p>Choose three drinks, win customers, switch bartenders, and race to <span class="money">$50</span>.</p><div class="actions"><button id="play-ai">Play vs AI</button><button data-mode="pvp">Local PvP</button><button id="tutorial">Play Tutorial</button><button id="deck" class="ghost">Build Deck</button><button id="rules" class="ghost">How to Play</button></div></section>`;$('#play-ai').onclick=difficultyScreen;document.querySelector('[data-mode="pvp"]').onclick=()=>start('pvp');$('#tutorial').onclick=startTutorial;$('#deck').onclick=builder;$('#rules').onclick=help}
function difficultyScreen(){app.innerHTML=`<section class="panel hero"><p class="eyebrow">PLAYER VS AI</p><h2>Choose Difficulty</h2><div class="grid difficulty-grid">${Object.entries(AI.DIFFICULTIES).map(([id,level])=>`<button class="card difficulty-card" data-difficulty="${id}"><h3>${level.name}</h3><p>${level.description}</p></button>`).join('')}</div><button id="back" class="ghost">Back</button></section>`;document.querySelectorAll('[data-difficulty]').forEach(button=>button.onclick=()=>start('ai',button.dataset.difficulty));$('#back').onclick=home}
function start(mode,aiDifficulty='normal'){const ids=load();if(!R.validateDeck(ids,D.drinks).ok)return builder();const aiName=mode==='ai'?`House AI (${AI.DIFFICULTIES[aiDifficulty].name})`:'Player 2';state={mode,aiDifficulty,round:0,customer:null,phase:'switch',players:[make('Player 1',ids),make(aiName,mode==='ai'?shuffle(starter()):ids)],turn:0,log:[]};nextRound()}
function instantiate(ids){return ids.map((id,i)=>({...D.drinks.find(d=>d.id===id),instanceId:`${id}-${i}-${Math.random().toString(36).slice(2)}`}))}
function make(name,ids){return{name,tips:0,tokens:1,nextThreshold:0,bartender:D.bartenders[0],deck:shuffle(instantiate(ids)),hand:[],selected:[],served:null}}
function nextRound(){state.round++;state.customer=null;state.phase='switch';state.turn=0;state.players.forEach(p=>{p.hand=[];p.selected=[];p.served=null});switchScreen()}
function switchScreen(){const p=state.players[state.turn],playerClass=state.turn===0?'player-one':'player-two';if(p.tokens<=0){finishSwitch();return}if(state.mode==='ai'&&state.turn===1){aiSwitch(p);finishSwitch();return}app.innerHTML=`<section class="panel ${playerClass}"><h2>${p.name}: bartender phase</h2><p>You have <b>${p.tokens}</b> switch token${p.tokens===1?'':'s'}. Switch now or save for a future round.</p><div class="grid">${D.bartenders.map((b,i)=>`<button class="card ${b===p.bartender?'selected':''}" data-b="${i}" aria-pressed="${b===p.bartender}"><span class="portrait" aria-hidden="true">${bartenderIcon(b.specialty)}</span><h3>${b.name}</h3><p class="traits">Specialty: ${b.specialty}</p><p>${b.passive}</p></button>`).join('')}</div><div class="actions"><button id="keep">Keep ${p.bartender.name} and Save Token</button></div></section>`;document.querySelectorAll('[data-b]').forEach(x=>x.onclick=()=>{const b=D.bartenders[+x.dataset.b];if(b===p.bartender)return;p.bartender=b;p.tokens--;finishSwitch()});$('#keep').onclick=finishSwitch}
function bartenderIcon(s){return({Beer:'🍺',Vodka:'🍸',Whiskey:'🥃',Rum:'🌴',Gin:'🌿',Tequila:'🌵',Wine:'🍷'})[s]||'🍹'}
function aiSwitch(p){const choice=AI.chooseBartender({current:p.bartender,bartenders:D.bartenders,deck:p.deck,tokens:p.tokens,tips:p.tips,difficulty:state.aiDifficulty});if(choice!==p.bartender){p.bartender=choice;p.tokens--}}
function finishSwitch(){if(state.turn===0){state.turn=1;if(state.mode==='pvp'&&state.players[1].tokens>0)return passSwitch();return switchScreen()}beginSelection()}
function passSwitch(){app.innerHTML=`<section class="panel pass privacy-screen"><div class="privacy-icon" aria-hidden="true">🔒</div><h2>Pass the device</h2><p>Player 2, choose your bartender privately. Player 1 should look away.</p><button id="ready">Player 2 Ready</button></section>`;$('#ready').onclick=switchScreen}
function beginSelection(){state.customer=D.customers[Math.floor(Math.random()*D.customers.length)];state.players.forEach(p=>{if(p.deck.length<7)p.deck=shuffle(instantiate(load()));p.hand=p.deck.splice(0,7)});state.turn=0;if(state.mode==='pvp')return passToSelection(0);chooseScreen()}
function chooseScreen(){const p=state.players[state.turn];state.phase='choose';if(state.mode==='ai'&&state.turn===1){p.selected=AI.chooseDrinks(p.hand,state.customer,p.bartender,state.aiDifficulty);p.served=R.best(p.selected,state.customer,p.bartender);resolve();return}renderChoose(p)}
function renderChoose(p){const playerClass=state.turn===0?'player-one':'player-two';app.innerHTML=`${scorebar()}<section class="customer"><h2>${state.customer.name}</h2><div class="prefs"><b class="love">♥ Loves ${state.customer.love}</b><b class="like">● Likes ${state.customer.like}</b><b class="dislike">▼ Dislikes ${state.customer.dislike}</b></div></section><section class="panel ${playerClass}"><h2>${p.name} · ${p.bartender.name}</h2><p class="status">Selected <strong id="count">${p.selected.length}/3</strong></p><div class="grid">${p.hand.map((d,i)=>card(d,i,p.selected.includes(d))).join('')}</div><button id="lock" class="lock" ${p.selected.length===3?'':'disabled'}>${p.selected.length===3?'Lock In 3 Drinks':`Choose ${3-p.selected.length} More`}</button></section>`;document.querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>{const d=p.hand[+el.dataset.card],i=p.selected.indexOf(d);if(i>=0)p.selected.splice(i,1);else if(p.selected.length<3)p.selected.push(d);renderChoose(p)});$('#lock').onclick=()=>{p.served=R.best(p.selected,state.customer,p.bartender);if(state.turn===0&&state.mode==='pvp')return passToSelection(1);if(state.turn===0){state.turn=1;chooseScreen();return}if(state.mode==='pvp')return confirmReveal();resolve()}}
function card(d,i,sel){return`<button class="card ${sel?'selected':''}" data-card="${i}" data-instance="${d.instanceId}" aria-pressed="${sel}"><h3>${d.name}</h3><p class="traits">${d.spirit} · ${d.styles.join(' · ')}</p><p class="price">$${d.price}</p></button>`}
function passToSelection(playerIndex){const p=state.players[playerIndex];state.turn=playerIndex;app.innerHTML=`<section class="panel pass privacy-screen"><div class="privacy-icon" aria-hidden="true">🔒</div><h2>Pass the device to ${p.name}</h2><p>The previous player's hand and choices are hidden. Only ${p.name} should continue.</p><button id="ready">${p.name} Ready</button></section>`;$('#ready').onclick=chooseScreen}
function confirmReveal(){if(!state.players.every(p=>p.served))throw new Error('Both players must lock in before reveal.');app.innerHTML=`${scorebar()}<section class="panel pass privacy-screen"><div class="privacy-icon" aria-hidden="true">✓</div><h2>Both players are locked in</h2><p>No selections are visible. Place the device where both players can see it, then reveal together.</p><button id="reveal">Reveal Drinks</button></section>`;$('#reveal').onclick=resolve}
function resolve(){const [a,b]=state.players;let winner;if(a.served.appeal>b.served.appeal)winner=0;else if(b.served.appeal>a.served.appeal)winner=1;else if(a.served.drink.price>b.served.drink.price)winner=0;else if(b.served.drink.price>a.served.drink.price)winner=1;else winner=Math.random()<.5?0:1;[a,b].forEach((p,i)=>{const before=p.tips,gain=R.payout(p.served.drink.price,i===winner);p.tips+=gain;p.tokens+=R.earned(before,p.tips)});state.log.unshift(`Round ${state.round}: ${state.players[winner].name} won.`);const gameover=a.tips>=R.WIN||b.tips>=R.WIN;app.innerHTML=`${scorebar()}<section class="panel result"><div class="trophy" aria-hidden="true">🏆</div><h2>${state.players[winner].name} wins the customer</h2>${[a,b].map((p,i)=>`<div class="result-row ${i===winner?'winner':''}"><b>${p.name}</b>: ${p.served.drink.name} · Appeal ${p.served.appeal}<span class="payout">+$${R.payout(p.served.drink.price,i===winner)}</span></div>`).join('')}<p>${gameover?'Last call! Match complete.':'Tips awarded. Ready for the next customer?'}</p><div class="actions"><button id="next">${gameover?'Main Menu':'Next Round'}</button></div></section>`;$('#next').onclick=gameover?home:nextRound}
function scorebar(){return`<section class="scorebar"><div class="score"><b>${state.players[0].name}</b><br><span class="money">$${state.players[0].tips}</span> · ${state.players[0].tokens} switch</div><strong>Round ${state.round}</strong><div class="score"><b>${state.players[1].name}</b><br><span class="money">$${state.players[1].tips}</span> · ${state.players[1].tokens} switch</div></section>`}
function builder(){draft=[...load()];renderBuilder()}function renderBuilder(msg=''){const counts=Object.fromEntries(D.drinks.map(d=>[d.id,draft.filter(x=>x===d.id).length]));app.innerHTML=`<section class="panel"><h2>Deck Builder</h2><p>Build exactly 30 cards, with no more than 3 copies of any drink.</p><p class="notice">${msg||`${draft.length}/30 cards · ${R.validateDeck(draft,D.drinks).message}`}</p><div class="builder-list">${D.drinks.map(d=>`<div class="builder-row"><span><b>${d.name}</b><br><small>${d.spirit} · $${d.price}</small></span><button data-minus="${d.id}" class="ghost">−</button><b>${counts[d.id]}</b><button data-plus="${d.id}" ${counts[d.id]>=3?'disabled':''}>+</button></div>`).join('')}</div><div class="actions"><button id="auto">Auto Build</button><button id="save">Save Deck</button><button id="clear" class="ghost">Clear</button><button id="cancel" class="ghost">Cancel</button></div></section>`;document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{if(draft.length<30)draft.push(b.dataset.plus);renderBuilder()});document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const i=draft.indexOf(b.dataset.minus);if(i>=0)draft.splice(i,1);renderBuilder()});$('#auto').onclick=()=>{draft=starter();renderBuilder('Legal starter deck generated.')};$('#clear').onclick=()=>{draft=[];renderBuilder()};$('#cancel').onclick=home;$('#save').onclick=()=>{const v=R.validateDeck(draft,D.drinks);if(!v.ok)return renderBuilder(v.message);save(draft);home()}}
function setTutorialFlag(key,value){try{localStorage.setItem(key,value)}catch(e){}}
function firstVisit(){let seen=false;try{seen=localStorage.getItem('blc.tutorialSeen')==='1'}catch(e){}if(seen)return home();tutorialWelcome()}
function tutorialWelcome(){state=null;app.innerHTML=`<section class="panel hero tutorial-welcome"><p class="eyebrow">FIRST SHIFT</p><h2>Learn the bar in eight quick steps</h2><p>The interactive tutorial takes only a few minutes. You can skip it now and replay it from the main menu anytime.</p><div class="actions"><button id="start-tutorial">Start Tutorial</button><button id="skip-tutorial" class="ghost">Skip for Now</button></div></section>`;$('#start-tutorial').onclick=startTutorial;$('#skip-tutorial').onclick=skipTutorial}
function startTutorial(){state=null;tutorial={step:0,seenPrefs:new Set(),lastPref:'',answer:null,selection:new Set(),servedAnswer:null,switchChoice:null,deckCount:27,deckAdds:{},victoryAnswer:null};setTutorialFlag('blc.tutorialSeen','1');renderTutorial()}
function skipTutorial(){setTutorialFlag('blc.tutorialSeen','1');home()}
function tutorialFrame(body){const step=T.STEPS[tutorial.step],progress=Math.round(((tutorial.step+1)/T.STEPS.length)*100);app.innerHTML=`<section class="panel tutorial-panel"><div class="tutorial-top"><div><p class="eyebrow">TUTORIAL ${tutorial.step+1}/${T.STEPS.length}</p><h2>${step.title}</h2></div><button id="skip-lesson" class="ghost">Exit Tutorial</button></div><div class="tutorial-progress" aria-label="Tutorial progress"><span style="width:${progress}%"></span></div><div class="tutorial-lesson">${body}</div></section>`;$('#skip-lesson').onclick=skipTutorial}
function tutorialContinue(enabled,label='Continue'){return`<button id="tutorial-next" ${enabled?'':'disabled'}>${label}</button>`}
function wireTutorialNext(){const next=$('#tutorial-next');if(next&&!next.disabled)next.onclick=advanceTutorial}
function advanceTutorial(){if(tutorial.step===T.STEPS.length-1)return completeTutorial();tutorial.step++;tutorial.answer=null;renderTutorial()}
function tutorialFeedback(answered,ok,success,failure){if(!answered)return'';return`<p class="tutorial-feedback ${ok?'correct':'incorrect'}">${ok?success:failure}</p>`}
function renderTutorial(){switch(T.STEPS[tutorial.step].id){case'customer':return tutorialCustomer();case'appeal':return tutorialAppeal();case'selection':return tutorialSelection();case'service':return tutorialService();case'tips':return tutorialTips();case'switch':return tutorialSwitch();case'deck':return tutorialDeck();case'victory':return tutorialVictory()}}
function tutorialCustomer(){const explanations={love:'Love adds +3 Appeal.',like:'Like adds +2 Appeal.',dislike:'Dislike subtracts 2 Appeal.'};tutorialFrame(`<div class="customer tutorial-customer"><h3>The Night Owl</h3><p>Tap all three preferences to inspect them.</p><div class="prefs"><button data-pref="love" class="pref-chip love ${tutorial.seenPrefs.has('love')?'seen':''}">♥ Loves Whiskey</button><button data-pref="like" class="pref-chip like ${tutorial.seenPrefs.has('like')?'seen':''}">● Likes Premium</button><button data-pref="dislike" class="pref-chip dislike ${tutorial.seenPrefs.has('dislike')?'seen':''}">▼ Dislikes Sweet</button></div></div><p class="tutorial-callout">${tutorial.lastPref?explanations[tutorial.lastPref]:'Customer preferences determine Appeal—not drink price.'}</p>${tutorialContinue(tutorial.seenPrefs.size===3)}`);document.querySelectorAll('[data-pref]').forEach(button=>button.onclick=()=>{tutorial.lastPref=button.dataset.pref;tutorial.seenPrefs.add(button.dataset.pref);tutorialCustomer()});wireTutorialNext()}
function tutorialAppeal(){const example=T.scoringExample(),correct=tutorial.answer===example.appeal;tutorialFrame(`<p>Old Fashioned matches <b>Love: Whiskey (+3)</b>, <b>Like: Premium (+2)</b>, and the bartender's <b>Whiskey specialty (+1)</b>. It does not match the Sweet dislike.</p><div class="tutorial-equation">3 + 2 + 1 = ?</div><div class="answer-grid">${[4,6,8].map(value=>`<button data-answer="${value}" class="${tutorial.answer===value?(value===example.appeal?'answer-correct':'answer-wrong'):''}">${value} Appeal</button>`).join('')}</div>${tutorialFeedback(tutorial.answer!==null,correct,'Correct—this drink has 6 Appeal.','Not quite. Add Love +3, Like +2, and specialty +1.')}${tutorialContinue(correct)}`);document.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>{tutorial.answer=+button.dataset.answer;tutorialAppeal()});wireTutorialNext()}
function tutorialSelection(){const drinks=[['Old Fashioned','Whiskey · Premium'],['Golden Lager','Beer · Cheap'],['Garden Gimlet','Gin · Fresh'],['Sunset Paloma','Tequila · Fruity'],['Velvet Merlot','Wine · Premium']];const valid=T.exactThree(tutorial.selection.size);tutorialFrame(`<p>Every round you draw seven cards. For this practice hand, select exactly three drinks.</p><p class="status">Selected <strong>${tutorial.selection.size}/3</strong></p><div class="grid tutorial-card-grid">${drinks.map((drink,i)=>`<button data-tutorial-card="${i}" class="card tutorial-card ${tutorial.selection.has(i)?'selected':''}" aria-pressed="${tutorial.selection.has(i)}"><h3>${drink[0]}</h3><p class="traits">${drink[1]}</p></button>`).join('')}</div><p class="tutorial-callout">In a match, only your highest-Appeal selection is served.</p>${tutorialContinue(valid)}`);document.querySelectorAll('[data-tutorial-card]').forEach(button=>button.onclick=()=>{const i=+button.dataset.tutorialCard;if(tutorial.selection.has(i))tutorial.selection.delete(i);else if(tutorial.selection.size<3)tutorial.selection.add(i);tutorialSelection()});wireTutorialNext()}
function tutorialService(){const options=[['old','Old Fashioned',6],['gimlet','Garden Gimlet',4],['lager','Golden Lager',1]],correct=tutorial.servedAnswer==='old';tutorialFrame(`<p>You selected these drinks. Tap the one the game will serve.</p><div class="grid tutorial-service-grid">${options.map(([id,name,appeal])=>`<button data-served="${id}" class="card tutorial-score-card ${tutorial.servedAnswer===id?(id==='old'?'answer-card-correct':'answer-card-wrong'):''}"><h3>${name}</h3><p class="tutorial-score">${appeal} Appeal</p></button>`).join('')}</div>${tutorialFeedback(tutorial.servedAnswer!==null,correct,'Correct—the highest-Appeal drink is served.','Choose the drink with the highest Appeal.')}${tutorialContinue(correct)}`);document.querySelectorAll('[data-served]').forEach(button=>button.onclick=()=>{tutorial.servedAnswer=button.dataset.served;tutorialService()});wireTutorialNext()}
function tutorialTips(){const correctValue=T.winnerTip(20),correct=tutorial.answer===correctValue;tutorialFrame(`<p>Your winning drink costs <b>$20</b>. The winner earns 25% of its price plus $2.</p><div class="tutorial-equation">$20 × 25% + $2 = ?</div><div class="answer-grid">${[5,7,10].map(value=>`<button data-tip="${value}" class="${tutorial.answer===value?(value===correctValue?'answer-correct':'answer-wrong'):''}">$${value}</button>`).join('')}</div>${tutorialFeedback(tutorial.answer!==null,correct,'Correct—you earn $7 in tips. The loser would earn 10% of their served drink.','Try again: 25% of $20 is $5, then add $2.')}${tutorialContinue(correct)}`);document.querySelectorAll('[data-tip]').forEach(button=>button.onclick=()=>{tutorial.answer=+button.dataset.tip;tutorialTips()});wireTutorialNext()}
function tutorialSwitch(){const chose=tutorial.switchChoice!==null,spent=tutorial.switchChoice==='switch';tutorialFrame(`<p>You start with one switch token and gain more when crossing $15, $30, and $45. Choose what to do before the round.</p><div class="token-demo"><b>Switch tokens: ${spent?0:1}</b></div><div class="actions"><button data-switch-choice="switch">Switch Bartender</button><button data-switch-choice="save" class="ghost">Keep Bartender</button></div>${chose?`<p class="tutorial-feedback correct">${spent?'You spent one token to adapt your specialty.':'You saved the token for a future round.'} Both are legal strategic choices.</p>`:''}${tutorialContinue(chose)}`);document.querySelectorAll('[data-switch-choice]').forEach(button=>button.onclick=()=>{tutorial.switchChoice=button.dataset.switchChoice;tutorialSwitch()});wireTutorialNext()}
function tutorialDeck(){const choices=[{id:'lager',name:'Golden Lager',traits:'Beer · Cheap',base:2},{id:'old',name:'Old Fashioned',traits:'Whiskey · Premium',base:3},{id:'gimlet',name:'Garden Gimlet',traits:'Gin · Fresh',base:1},{id:'paloma',name:'Sunset Paloma',traits:'Tequila · Fruity',base:0}],valid=T.legalDeckCount(tutorial.deckCount),remaining=30-tutorial.deckCount;tutorialFrame(`<p>Your deck has 27 cards. Select the final three drinks. No drink may exceed ${T.maxCopies} copies.</p><div class="deck-demo"><strong>${tutorial.deckCount}/30</strong><span>${remaining?`${remaining} slots remaining`:'legal deck complete'}</span></div><div class="grid tutorial-deck-grid">${choices.map(card=>{const copies=card.base+(tutorial.deckAdds[card.id]||0),canAdd=T.canAddCopy(copies,tutorial.deckCount);return`<button data-deck-add="${card.id}" class="card tutorial-deck-card" ${canAdd?'':'disabled'}><h3>${card.name}</h3><p class="traits">${card.traits}</p><p class="copy-count">Copies: ${copies}/${T.maxCopies}</p><span class="add-label">${copies>=T.maxCopies?'Copy Limit Reached':valid?'Deck Full':'+ Add to Deck'}</span></button>`}).join('')}</div><div class="actions"><button id="reset-deck-lesson" class="ghost" ${tutorial.deckCount===27?'disabled':''}>Reset Choices</button>${tutorialContinue(valid)}</div>`);document.querySelectorAll('[data-deck-add]').forEach(button=>button.onclick=()=>{const id=button.dataset.deckAdd;tutorial.deckAdds[id]=(tutorial.deckAdds[id]||0)+1;tutorial.deckCount++;tutorialDeck()});const reset=$('#reset-deck-lesson');if(reset&&!reset.disabled)reset.onclick=()=>{tutorial.deckAdds={};tutorial.deckCount=27;tutorialDeck()};wireTutorialNext()}
function tutorialVictory(){const correct=tutorial.victoryAnswer===T.winTarget;tutorialFrame(`<p>One last question: how many dollars in tips wins the match?</p><div class="answer-grid">${[30,50,100].map(value=>`<button data-victory="${value}" class="${tutorial.victoryAnswer===value?(value===T.winTarget?'answer-correct':'answer-wrong'):''}">$${value}</button>`).join('')}</div>${tutorialFeedback(tutorial.victoryAnswer!==null,correct,'Correct—first to $50 wins immediately.','Not quite. Last Call happens at $50.')}${tutorialContinue(correct,'Finish Tutorial')}`);document.querySelectorAll('[data-victory]').forEach(button=>button.onclick=()=>{tutorial.victoryAnswer=+button.dataset.victory;tutorialVictory()});wireTutorialNext()}
function completeTutorial(){setTutorialFlag('blc.tutorialSeen','1');setTutorialFlag('blc.tutorialComplete','1');tutorial=null;app.innerHTML=`<section class="panel hero tutorial-complete"><div class="privacy-icon" aria-hidden="true">✓</div><p class="eyebrow">TRAINING COMPLETE</p><h2>You're ready for last call</h2><p>You can replay the tutorial anytime or practice against Easy AI.</p><div class="actions"><button id="practice">Practice vs Easy AI</button><button id="tutorial-menu" class="ghost">Main Menu</button></div></section>`;$('#practice').onclick=()=>start('ai','easy');$('#tutorial-menu').onclick=home}
function help(){app.innerHTML=`<section class="panel hero"><h2>How to Play</h2><p>Each round, a customer Loves one trait (+3), Likes one (+2), and Dislikes one (−2). Your bartender specialty adds +1. Price never adds Appeal; it only breaks ties.</p><p>Choose exactly three drinks. Your highest-Appeal drink is served. The winner earns 25% of its price + $2; the loser earns 10%. Start with one switch token and gain more when crossing $15, $30, and $45. First to $50 wins.</p><div class="actions"><button id="replay-tutorial">Play Tutorial</button><button id="back" class="ghost">Back</button></div></section>`;$('#replay-tutorial').onclick=startTutorial;$('#back').onclick=home}
$('#sound').onclick=e=>{e.currentTarget.setAttribute('aria-pressed',e.currentTarget.getAttribute('aria-pressed')==='false'?'true':'false');e.currentTarget.textContent=e.currentTarget.getAttribute('aria-pressed')==='true'?'Sound: Off':'Sound: On'};firstVisit();
})();
